easy_admin:
    user:
        name_property_path: 'username'
    site_name: 'Lille Judo Admin'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        assets:
            favicon: '/assets/favicon.ico'
        menu:
            - { label: 'Accueil Site', route: 'accueil', icon: 'home' }
            - { label: 'Boutique'}
            - { entity: 'Boutique', label: 'Boutique', icon: 'shopping-cart' }
            - { label: 'Club' }
            - label: 'Histoire'
              children: ['HistoireClub', 'HistoirePresidents', 'HistoirePersonnalites', 'HistoireEnseignement']
            - { entity: 'Professeurs', label: 'Enseignants', icon: 'chalkboard-teacher' }
            - { entity: 'Bureau', icon: 'laptop-house' }
            - { label: 'Disciplines' }
            - { label: 'Inscription' }
            - { entity: 'FicheInscription', label: "Fiche d'inscription", icon: 'copy' }
            - { label: 'Actualités' }
            - { entity: 'Post', icon: 'tag' }
            - { entity: 'PostClub', icon: 'tag' }
            - { entity: 'PostNatio', icon: 'globe' }
            - { label: 'Documents' }
            - { entity: 'Gallery', icon: 'images' }
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    entities:
        Post:
            class: App\Entity\Post
            label: 'Newsletter'
            list:
                fields:
                    - { property: 'title', label: 'Titre', type: 'string' }
                    - { property: 'body', label: 'Corps', type: 'text' }
                    - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.post_images%' }
                    - { property: 'createdAt', label: 'Date de création', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Date de mise à jour', type: 'datetime' }
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'body', label: 'Corps', type: 'fos_ckeditor' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', type_options: { allow_delete: false }  }
        PostClub:
            class: App\Entity\PostClub
            label: 'Actualités Club'
            list:
                fields:
                    - { property: 'title', label: 'Titre', type: 'string' }
                    - { property: 'body', label: 'Corps', type: 'text' }
                    - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.post_club_images%' }
                    - { property: 'createdAt', label: 'Date de création', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Date de mise à jour', type: 'datetime' }
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'body', label: 'Corps', type: 'fos_ckeditor' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', type_options: { allow_delete: false }  }
        PostNatio:
              class: App\Entity\PostNatio
              label: 'Actualités Nationale/Internationale'
              list:
                  fields:
                      - { property: 'title', label: 'Titre', type: 'string' }
                      - { property: 'body', label: 'Corps', type: 'text' }
                      - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.post_club_images%' }
                      - { property: 'createdAt', label: 'Date de création', type: 'datetime' }
                      - { property: 'updatedAt', label: 'Date de mise à jour', type: 'datetime' }
              form:
                  fields:
                      - { property: 'title', label: 'Titre' }
                      - { property: 'body', label: 'Corps', type: 'fos_ckeditor' }
                      - { property: 'imageFile', label: 'Image', type: 'vich_image', type_options: { allow_delete: false }  }
        Professeurs:
            class: App\Entity\Professeurs
            label: 'Enseignants'
            list:
                fields:
                    - { property: 'nom', label: 'Nom', type: 'string' }
                    - { property: 'prenom', label: 'Prénom', type: 'string' }
                    - { property: 'grade', label: 'Grade', type: 'string' }
                    - { property: 'diplome', label: 'Diplomes', type: 'string' }
                    - { property: 'role', label: 'Role', type: 'string' }
                    - { property: 'image', label: 'Image', type: 'image' , base_path: '%app.path.professeurs_images%' }
            form:
                fields:
                    - { property: 'nom', label: 'Nom' }
                    - { property: 'prenom', label: 'Prénom' }
                    - { property: 'grade', label: 'Grade' }
                    - { property: 'diplome', label: 'Diplomes' }
                    - { property: 'role', label: 'Role' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', type_options: { allow_delete: false }  }
        Bureau:
            class: App\Entity\Bureau
            list:
                fields:
                    - { property: 'nom', label: 'Nom', type: 'string' }
                    - { property: 'prenom', label: 'Prénom', type: 'string' }
                    - { property: 'role', label: 'Role', type: 'string' }
                    - { property: 'image', label: 'Image', type: 'image' , base_path: '%app.path.bureau_images%' }
            form:
                fields:
                    - { property: 'nom', label: 'Nom' }
                    - { property: 'prenom', label: 'Prénom' }
                    - { property: 'role', label: 'Role', type: 'choice', type_options: { choices: { Président: 'Président', Trésorier: 'Trésorier', Secrétaire: 'Secrétaire', 'Secrétaire Adjointe': 'Secrétaire Adjointe' } } }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', type_options: { allow_delete: false }  }
        Gallery:
            class: App\Entity\Gallery
            label: 'Galerie'
            list:
                fields:
                    - { property: 'name', label: 'Nom', type: 'string' }
                    - { property: 'galleryImages', label: 'Images' }
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'galleryImages', label: 'Images', type: 'collection', type_options: { entry_type: 'App\Form\GalleryImageType', by_reference: false } }
        HistoireClub:
            class: App\Entity\HistoriqueClub
            label: 'Historique du Club'
            list:
                fields:
                    - { property: 'titre', label: 'Titre', type: 'string' }
                    - { property: 'annee', label: 'Année', type: 'integer' }
                    - { property: 'texte', label: 'Texte', type: 'text' }
            form:
                fields:
                    - { property: 'titre', label: 'Titre' }
                    - { property: 'annee', label: 'Année', type: 'integer' }
                    - { property: 'texte', label: 'Texte', type: 'textarea' }
        HistoirePresidents:
            class: App\Entity\HistoriquePresidents
            label: 'Les Divers Présidents'
            list:
                fields:
                    - { property: 'titre', label: 'Nom', type: 'string' }
                    - { property: 'annee', label: 'Année', type: 'integer' }
                    - { property: 'texte', label: 'Texte', type: 'text' }
            form:
                fields:
                    - { property: 'titre', label: 'Nom' }
                    - { property: 'annee', label: 'Année', type: 'integer' }
                    - { property: 'texte', label: 'Texte', type: 'textarea' }
        HistoirePersonnalites:
            class: App\Entity\HistoriquePersonnalites
            label: 'Quelques personnalités marquantes'
            list:
                fields:
                    - { property: 'titre', label: 'Nom', type: 'string' }
                    - { property: 'texte', label: 'Texte', type: 'text' }
            form:
                fields:
                    - { property: 'titre', label: 'Nom' }
                    - { property: 'texte', label: 'Texte', type: 'textarea' }
        HistoireEnseignement:
            class: App\Entity\HistoriqueEnseignement
            label: "L'enseignement"
            list:
                fields:
                    - { property: 'texte', label: 'Texte', type: 'text' }
            form:
                fields:
                    - { property: 'texte', label: 'Texte', type: 'textarea' }
        FicheInscription:
            class: App\Entity\FicheInscription
            label: "Fiche d'inscription"
            list:
                fields:
                    - { property: 'fiche', label: 'Fiche', type: 'string' }
            form:
                fields:
                    - { property: 'ficheFile', label: 'Fiche', type: 'vich_file', type_options: { allow_delete: false } }
        Boutique:
            class: App\Entity\Boutique
            list:
                fields:
                    - { property: 'objet', label: 'Objet', type: 'string' }
                    - { property: 'prix', label: 'Prix', type: 'string' }
                    - { property: 'image', label: 'Image', type: 'image' , base_path: '%app.path.boutique_images%' }
            form:
                fields:
                    - { property: 'objet', label: 'Objet' }
                    - { property: 'prix', label: 'Prix', type: 'money' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', type_options: { allow_delete: false, required: true }  }
