easy_admin:
    user:
        name_property_path: 'username'
    site_name: 'Lille Judo Admin'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        assets:
            favicon: '/assets/favicon.ico'
        menu:
            - { label: 'Accueil Site', route: 'accueil', icon: 'home' }
            - { label: 'Club' }
            - label: 'Histoire'
              children: ['HistoireClub']
            - { entity: 'Professeurs', label: 'Enseignants', icon: 'chalkboard-teacher' }
            - { entity: 'Bureau', icon: 'laptop-house' }
            - { label: 'Disciplines' }
            - { label: 'Inscription' }
            - { label: 'Actualités' }
            - { entity: 'Post', icon: 'tag' }
            - { entity: 'PostClub', icon: 'tag' }
            - { entity: 'PostNatio', icon: 'globe' }
            - { label: 'Documents' }
            - { entity: 'Gallery', icon: 'images' }
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    entities:
        Post:
            class: App\Entity\Post
            label: 'Newsletter'
            list:
                fields:
                    - { property: 'title', label: 'Titre', type: 'string' }
                    - { property: 'body', label: 'Corps', type: 'text' }
                    - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.post_images%' }
                    - { property: 'createdAt', label: 'Date de création', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Date de mise à jour', type: 'datetime' }
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'body', label: 'Corps', type: 'fos_ckeditor' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image' }
        PostClub:
            class: App\Entity\PostClub
            label: 'Actualités Club'
            list:
                fields:
                    - { property: 'title', label: 'Titre', type: 'string' }
                    - { property: 'body', label: 'Corps', type: 'text' }
                    - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.post_club_images%' }
                    - { property: 'createdAt', label: 'Date de création', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Date de mise à jour', type: 'datetime' }
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'body', label: 'Corps', type: 'fos_ckeditor' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image' }
        PostNatio:
              class: App\Entity\PostNatio
              label: 'Actualités Nationale/Internationale'
              list:
                  fields:
                      - { property: 'title', label: 'Titre', type: 'string' }
                      - { property: 'body', label: 'Corps', type: 'text' }
                      - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.post_club_images%' }
                      - { property: 'createdAt', label: 'Date de création', type: 'datetime' }
                      - { property: 'updatedAt', label: 'Date de mise à jour', type: 'datetime' }
              form:
                  fields:
                      - { property: 'title', label: 'Titre' }
                      - { property: 'body', label: 'Corps', type: 'fos_ckeditor' }
                      - { property: 'imageFile', label: 'Image', type: 'vich_image' }
        Professeurs:
            class: App\Entity\Professeurs
            label: 'Enseignants'
            list:
                fields:
                    - { property: 'nom', label: 'Nom', type: 'string' }
                    - { property: 'prenom', label: 'Prénom', type: 'string' }
                    - { property: 'grade', label: 'Grade', type: 'string' }
                    - { property: 'diplome', label: 'Diplomes', type: 'string' }
                    - { property: 'role', label: 'Role', type: 'string' }
                    - { property: 'image', label: 'Image', type: 'image' , base_path: '%app.path.professeurs_images%' }
            form:
                fields:
                    - { property: 'nom', label: 'Nom' }
                    - { property: 'prenom', label: 'Prénom' }
                    - { property: 'grade', label: 'Grade' }
                    - { property: 'diplome', label: 'Diplomes' }
                    - { property: 'role', label: 'Role' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image' }
        Bureau:
            class: App\Entity\Bureau
            list:
                fields:
                    - { property: 'nom', label: 'Nom', type: 'string' }
                    - { property: 'prenom', label: 'Prénom', type: 'string' }
                    - { property: 'role', label: 'Role', type: 'string' }
                    - { property: 'image', label: 'Image', type: 'image' , base_path: '%app.path.bureau_images%' }
            form:
                fields:
                    - { property: 'nom', label: 'Nom' }
                    - { property: 'prenom', label: 'Prénom' }
                    - { property: 'role', label: 'Role', type: 'choice', type_options: { choices: { Président: 'Président', Trésorier: 'Trésorier', Secrétaire: 'Secrétaire', 'Secrétaire Adjointe': 'Secrétaire Adjointe' } } }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image' }
        Gallery:
            class: App\Entity\Gallery
            label: 'Galerie'
            list:
                fields:
                    - { property: 'name', label: 'Nom', type: 'string' }
                    - { property: 'galleryImages', label: 'Images' }
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'galleryImages', label: 'Images', type: 'collection', type_options: { entry_type: 'App\Form\GalleryImageType', by_reference: false } }
        HistoireClub:
            class: App\Entity\HistoriqueClub
            label: 'Historique du Club'
            list:
                fields:
                    - { property: 'titre', label: 'Titre', type: 'string' }
                    - { property: 'annee', label: 'Année', type: 'integer' }
                    - { property: 'texte', label: 'Texte', type: 'text' }
            form:
                fields:
                    - { property: 'titre', label: 'Titre' }
                    - { property: 'annee', label: 'Année', type: 'integer' }
                    - { property: 'texte', label: 'Texte', type: 'textarea' }