easy_admin:
    user:
        name_property_path: 'username'
    site_name: 'Lille Judo Admin'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        menu:
            - { label: 'Accueil Site', route: 'accueil', icon: 'home' }
            - { entity: 'Post', icon: 'tag' }
            - { entity: 'PostClub', icon: 'tag' }
            - { entity: 'PostNatio', icon: 'tag' }
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    entities:
        Post:
            class: App\Entity\Post
            list:
                fields:
                    - { property: 'title', label: 'Titre', type: 'string' }
                    - { property: 'body', label: 'Corps', type: 'text' }
                    - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.post_images%' }
                    - { property: 'createdAt', label: 'Date de création', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Date de mise à jour', type: 'datetime' }
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'body', label: 'Corps', type: 'fos_ckeditor' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image' }
        PostClub:
            class: App\Entity\PostClub
            list:
                fields:
                    - { property: 'title', label: 'Titre', type: 'string' }
                    - { property: 'body', label: 'Corps', type: 'text' }
                    - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.post_club_images%' }
                    - { property: 'createdAt', label: 'Date de création', type: 'datetime' }
                    - { property: 'updatedAt', label: 'Date de mise à jour', type: 'datetime' }
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'body', label: 'Corps', type: 'fos_ckeditor' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image' }
        PostNatio:
              class: App\Entity\PostNatio
              list:
                  fields:
                      - { property: 'title', label: 'Titre', type: 'string' }
                      - { property: 'body', label: 'Corps', type: 'text' }
                      - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.post_club_images%' }
                      - { property: 'createdAt', label: 'Date de création', type: 'datetime' }
                      - { property: 'updatedAt', label: 'Date de mise à jour', type: 'datetime' }
              form:
                  fields:
                      - { property: 'title', label: 'Titre' }
                      - { property: 'body', label: 'Corps', type: 'fos_ckeditor' }
                      - { property: 'imageFile', label: 'Image', type: 'vich_image' }