# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar: full
    toolbars:
        items:
            full.insert: ['Image', 'Flash', 'Table', 'HorizontalRule', 'SpecialChar', 'PageBreak', 'Iframe']
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
