vich_uploader:
    db_driver: orm

    mappings:
        post_images:
            uri_prefix: '%app.path.post_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_images%'
        post_club_images:
            uri_prefix: '%app.path.post_club_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_club_images%'
        post_natio_images:
            uri_prefix: '%app.path.post_natio_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_natio_images%'
        profeseurs_images:
            uri_prefix: '%app.path.professeurs_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.professeurs_images%'
        bureau_images:
            uri_prefix: '%app.path.bureau_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.bureau_images%'
        gallery_images:
            uri_prefix: '%app.path.gallery_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.gallery_images%'
        boutique_images:
            uri_prefix: '%app.path.boutique_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.boutique_images%'
        passage_grades_images:
            uri_prefix: '%app.path.passage_grades_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.passage_grades_images%'
        fiche_inscription:
            uri_prefix: '%app.path.fiche_inscription%'
            upload_destination: '%kernel.project_dir%/public%app.path.fiche_inscription%'
        boutique_fiche:
            uri_prefix: '%app.path.boutique_fiche%'
            upload_destination: '%kernel.project_dir%/public%app.path.boutique_fiche%'
        documents_utiles:
            uri_prefix: '%app.path.documents_utiles%'
            upload_destination: '%kernel.project_dir%/public%app.path.documents_utiles%'
        documents_competition:
            uri_prefix: '%app.path.documents_competition%'
            upload_destination: '%kernel.project_dir%/public%app.path.documents_competition%'
        documents_evenement:
            uri_prefix: '%app.path.documents_evenement%'
            upload_destination: '%kernel.project_dir%/public%app.path.documents_evenement%'
        inscription_avant:
            uri_prefix: '%app.path.inscription_avant%'
            upload_destination: '%kernel.project_dir%/public%app.path.inscription_avant%'
        inscription_pendant:
            uri_prefix: '%app.path.inscription_pendant%'
            upload_destination: '%kernel.project_dir%/public%app.path.inscription_pendant%'
        inscription_apres:
            uri_prefix: '%app.path.inscription_apres%'
            upload_destination: '%kernel.project_dir%/public%app.path.inscription_apres%'