vich_uploader:
    db_driver: orm

    mappings:
        post_images:
            uri_prefix: '%app.path.post_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_images%'
        post_club_images:
            uri_prefix: '%app.path.post_club_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_club_images%'
        post_natio_images:
            uri_prefix: '%app.path.post_natio_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_natio_images%'
        profeseurs_images:
            uri_prefix: '%app.path.professeurs_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.professeurs_images%'
        bureau_images:
            uri_prefix: '%app.path.bureau_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.bureau_images%'
        gallery_images:
            uri_prefix: '%app.path.gallery_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.gallery_images%'
        fiche_inscription:
            uri_prefix: '%app.path.fiche_inscription%'
            upload_destination: '%kernel.project_dir%/public%app.path.fiche_inscription%'