vich_uploader:
    db_driver: orm

    mappings:
        post_images:
            uri_prefix: '%app.path.post_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_images%'
        post_club_images:
            uri_prefix: '%app.path.post_club_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_club_images%'
        post_natio_images:
            uri_prefix: '%app.path.post_natio_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_natio_images%'
        post_profeseurs_images:
            uri_prefix: '%app.path.post_professeurs_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_professeurs_images%'