version: '3'

services:
  mysql1.6:
    image: mysql:5.6
    container_name: lillejudo-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'lillejudo'
#    volumes:
#      - lillejudo-db:/var/lib/mysql16


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql1.6
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  db-volumes: {}