# Usually part of config.yml
# Follow this instructions in order to have al needed id and token:
# https://stackoverflow.com/questions/17197970/facebook-permanent-page-access-token/28418469#28418469

social_post:
    publish_on: [facebook]
    providers:
        facebook:
            app_id: "987576148384955"
            app_secret: "917cdc3e768106bc470d3d740000f43a"
            default_access_token: "EAAOCMf2DXLsBABvJSZBD1aTHQgUNp9NR9qcMLic1fUtHBsc1tSwRcM4D4RV6KiUjYXPPkQJpcrpEJbnl6Dp90uq22o2ZA7lWFqAWzjYxjsBvTPF6uaE2TlzCfCKntHnavzezUMVTvU7nTO64nxSubcLQlseVAiT1qXgZC5Q0AZDZD"
            page_id: "335783152973"
            enable_beta_mode: true
            persistent_data_handler: "memory"         # Optional, also supports "session". Default is "memory".
            pseudo_random_string_generator: "openssl" # Optional, also supports "mcrypt" and "urandom". Default is "openssl".
            http_client_handler: "curl"               # Optional, also supports "stream" and "guzzle". Default is "curl".